import { CropProfile, CropId } from '../types/telemetry';

export const CROP_DATABASE: Record<CropId, CropProfile> = {
  green_chilli: {
    id: 'green_chilli',
    name: 'Green Chilli',
    regionalName: 'Kesa Jolokia (কেঁচা জলকীয়া)',
    category: 'Spices',
    idealTempMin: 7,
    idealTempMax: 10,
    idealRHMin: 90,
    idealRHMax: 95,
    idealO2Min: 3.0,
    idealO2Max: 5.0,
    maxCO2Limit: 5.0,
    respirationRate: 'Moderate',
    ethyleneSensitivity: 'Medium',
    standardShelfLifeDays: 5,
    scabShelfLifeDays: 28,
    icon: '🌶️',
  },
  bhut_jolokia: {
    id: 'bhut_jolokia',
    name: 'Bhut Jolokia (Ghost Pepper)',
    regionalName: 'Bih Jolokia / Naga Mircha (ভূত জলকীয়া)',
    category: 'Spices',
    idealTempMin: 8,
    idealTempMax: 11,
    idealRHMin: 88,
    idealRHMax: 93,
    idealO2Min: 3.0,
    idealO2Max: 4.5,
    maxCO2Limit: 4.0,
    respirationRate: 'Moderate',
    ethyleneSensitivity: 'High',
    standardShelfLifeDays: 4,
    scabShelfLifeDays: 25,
    icon: '🔥',
  },
  cabbage: {
    id: 'cabbage',
    name: 'Cabbage',
    regionalName: 'Bandhakobi (বন্ধাকবি)',
    category: 'Vegetables',
    idealTempMin: 0,
    idealTempMax: 2,
    idealRHMin: 95,
    idealRHMax: 98,
    idealO2Min: 2.0,
    idealO2Max: 3.5,
    maxCO2Limit: 5.0,
    respirationRate: 'Moderate',
    ethyleneSensitivity: 'High',
    standardShelfLifeDays: 7,
    scabShelfLifeDays: 45,
    icon: '🥬',
  },
  french_beans: {
    id: 'french_beans',
    name: 'French Beans',
    regionalName: 'Lobiya / Matarmah (লেচেৰা মাহ)',
    category: 'Vegetables',
    idealTempMin: 5,
    idealTempMax: 8,
    idealRHMin: 90,
    idealRHMax: 95,
    idealO2Min: 2.5,
    idealO2Max: 4.5,
    maxCO2Limit: 6.0,
    respirationRate: 'High',
    ethyleneSensitivity: 'High',
    standardShelfLifeDays: 4,
    scabShelfLifeDays: 24,
    icon: '🫘',
  },
  tomatoes: {
    id: 'tomatoes',
    name: 'Tomatoes (Mature Green/Pink)',
    regionalName: 'Bilahi (বিলাহী)',
    category: 'Vegetables',
    idealTempMin: 10,
    idealTempMax: 13,
    idealRHMin: 90,
    idealRHMax: 95,
    idealO2Min: 3.0,
    idealO2Max: 5.0,
    maxCO2Limit: 3.0,
    respirationRate: 'High',
    ethyleneSensitivity: 'High',
    standardShelfLifeDays: 6,
    scabShelfLifeDays: 32,
    icon: '🍅',
  },
  leafy_mustard: {
    id: 'leafy_mustard',
    name: 'Leafy Mustard Greens',
    regionalName: 'Lai Xaak (লাই শাক)',
    category: 'Vegetables',
    idealTempMin: 0,
    idealTempMax: 2,
    idealRHMin: 95,
    idealRHMax: 100,
    idealO2Min: 1.5,
    idealO2Max: 3.0,
    maxCO2Limit: 7.0,
    respirationRate: 'Very High',
    ethyleneSensitivity: 'High',
    standardShelfLifeDays: 2,
    scabShelfLifeDays: 18,
    icon: '🌱',
  },
  ginger: {
    id: 'ginger',
    name: 'Fresh Ginger',
    regionalName: 'Ada (আদা)',
    category: 'Tubers',
    idealTempMin: 12,
    idealTempMax: 14,
    idealRHMin: 85,
    idealRHMax: 90,
    idealO2Min: 4.0,
    idealO2Max: 6.0,
    maxCO2Limit: 5.0,
    respirationRate: 'Low',
    ethyleneSensitivity: 'Low',
    standardShelfLifeDays: 14,
    scabShelfLifeDays: 75,
    icon: '🫚',
  },
  turmeric: {
    id: 'turmeric',
    name: 'Lakadong Turmeric',
    regionalName: 'Halodhi (হালধি)',
    category: 'Tubers',
    idealTempMin: 12,
    idealTempMax: 15,
    idealRHMin: 85,
    idealRHMax: 90,
    idealO2Min: 4.0,
    idealO2Max: 6.0,
    maxCO2Limit: 5.0,
    respirationRate: 'Low',
    ethyleneSensitivity: 'Low',
    standardShelfLifeDays: 18,
    scabShelfLifeDays: 90,
    icon: '🟡',
  },
};

export const CROP_LIST = Object.values(CROP_DATABASE);
