export type WeatherConditionType =
  | 'Sunny'
  | 'Partly Sunny'
  | 'Partly Cloudy'
  | 'Cloudy'
  | 'Rain'
  | 'Light Rain'
  | 'Rain / Monsoon'
  | 'Heavy Storm'
  | 'Thunderstorm'
  | 'Scattered Thunderstorm'
  | 'Clear Sky Night'
  | 'Clear Night'
  | 'Partly Cloudy Night';

export interface HourlyForecast {
  time: string; // ISO string
  hourLabel: string; // e.g. 'Now', '8 AM', '9 AM'
  temperature: number; // °C
  relativeHumidity: number; // %
  precipitationProbability: number; // %
  rainMm: number; // mm
  cloudCoverPercent: number; // %
  solarRadiationWatts: number; // W/m²
  windSpeed: number; // km/h
  isClearSkyNight: boolean; // Suitable for Radiative Sky Cooling
  optimalForCompressorHeatDump: boolean; // Low ambient T/RH window
  weatherCondition: WeatherConditionType;
}

export interface DailyForecast {
  date: string; // YYYY-MM-DD
  dayOfWeek: string; // 'Today', 'Sat', 'Sun', etc.
  formattedDate: string; // 'Today' or 'Saturday, Sep 19'
  tempMax: number;
  tempMin: number;
  avgHumidity: number;
  rainProbabilityMax: number;
  totalPrecipitationMm: number;
  avgCloudCover: number;
  solarHoursEstimate: number; // Peak sun hours
  estimatedSolarGenerationKwh: number; // Generated by cold store PV array
  weatherCondition: WeatherConditionType;
  conditionText: string; // e.g. 'Partly sunny', 'Heavy thunderstorm with rain'
  isSevereMonsoonDay: boolean; // Triggers early PCM pre-freezing
  predictedCoolingStrategy: string;

  // Detailed Google Weather metrics
  windSpeedMax: number; // km/h
  windDirection: string; // e.g. 'northeast', 'southwest'
  windDirectionDeg: number; // 0-360 degrees
  windDescription: string; // e.g. 'Calm • From northeast'
  uvIndexMax: number; // 0-11+
  uvDescription: string; // 'Low', 'Moderate', 'High', 'Very high', 'Extreme'
  sunrise: string; // '5:29 AM'
  sunset: string; // '5:43 PM'
  hourlyData: HourlyForecast[]; // 24-hour breakdown for this day
}

export interface WeatherData {
  latitude: number;
  longitude: number;
  timezone: string;
  elevation: number;
  currentTemp: number;
  currentRH: number;
  currentRainProb: number;
  currentSolarWatts: number;
  currentCondition?: WeatherConditionType;
  currentConditionText?: string;
  daily: DailyForecast[];
  hourly: HourlyForecast[];
  lastFetched: string;
  isRealTime: boolean;
}

