export interface HourlyForecast {
  time: string; // ISO string
  temperature: number; // °C
  relativeHumidity: number; // %
  precipitationProbability: number; // %
  rainMm: number; // mm
  cloudCoverPercent: number; // %
  solarRadiationWatts: number; // W/m²
  isClearSkyNight: boolean; // Suitable for Radiative Sky Cooling
  optimalForCompressorHeatDump: boolean; // Low ambient T/RH window
}

export interface DailyForecast {
  date: string; // YYYY-MM-DD
  dayOfWeek: string;
  tempMax: number;
  tempMin: number;
  avgHumidity: number;
  rainProbabilityMax: number;
  totalPrecipitationMm: number;
  avgCloudCover: number;
  solarHoursEstimate: number; // Peak sun hours
  estimatedSolarGenerationKwh: number; // Generated by cold store PV array
  weatherCondition: 'Sunny' | 'Partly Cloudy' | 'Rain / Monsoon' | 'Heavy Storm' | 'Clear Sky Night';
  isSevereMonsoonDay: boolean; // Triggers early PCM pre-freezing
  predictedCoolingStrategy: string;
}

export interface WeatherData {
  latitude: number;
  longitude: number;
  timezone: string;
  elevation: number;
  currentTemp: number;
  currentRH: number;
  currentRainProb: number;
  currentSolarWatts: number;
  daily: DailyForecast[];
  hourly: HourlyForecast[];
  lastFetched: string;
  isRealTime: boolean;
}
